name: Sync Pull Request to Azure Boards

on:
  pull_request:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: github.com/RPagels/CoreWithGitHubWorkflow/new/master
      env:
        ado_token: '${{018b1d5d64db91d3be252a38ee832c9a316d24ec}}'   
        github_token: '${{aoidj5zzmn7mnxurzqbs4uhhbd7xfkda6ucl75vunkftmdk53agq}}'    
        ado_organization: 'privatepreview'
        ado_project: 'Agile'
        ado_wit: 'Pull Request' 
        ado_new_state: 'New'
        ado_active_state: 'Active'
        ado_close_state: 'Closed'
