#
name: Sync Pull Request to Azure Boards

on:
  pull_request:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: RPagels/CoreWithGitHubWorkflow@master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.GH_TOKEN }}'    
        ado_organization: 'privatepreview'
        ado_project: 'Agile'
        ado_wit: 'Pull Request' 
        ado_new_state: 'New'
        ado_active_state: 'Active'
        ado_close_state: 'Closed'
